@baseUri = https://AZ_FUNC_NAME.azurewebsites.net/api
@contentType = application/json
@sampleAppId = 81283b9c-0d85-436c-94ce-3156b0d885bb
@sampleAppObjectId = ea66cb30-f6a9-443f-b18b-cdca6bb980b8
@sampleSPObjectId = f82049a3-f071-4530-a8a2-576ffcefd600
@userObjectId = 9c5918c7-ef03-4059-a49e-aa6e6d761423
# Example requests starts below

###
# Lists all applications in the directory. However, this API 
# doesn't do paging, therefore, only the first page of info is returned.
GET {{baseUri}}/applications HTTP/1.1
Content-Type: {{contentType}}

### 
GET {{baseUri}}/applications/app-ids/{{sampleAppId}} HTTP/1.1
Content-Type: {{contentType}}

###
POST {{baseUri}}/applications HTTP/1.1
Content-Type: application/json

{
    "Description": "Venus-X",
    "DisplayName": "Venus-X",
    "Tags": ["Venus", "Automated"]
}


###
POST {{baseUri}}/applications/{{sampleAppObjectId}}/password-credentials HTTP/1.1
Content-Type: application/json

{
    "DisplayName": "CurrentPassword",
    "Hint": "This is my smart hint!",
    "StartDateTime": "5/25/2021 8:00:00 AM +00:00",
    "EndDateTime": "7/21/2021 9:22:53 AM +00:00"
}

###
DELETE  {{baseUri}}/applications/{{sampleAppObjectId}}/password-credentials/66a4ae18-bca5-4c19-ab35-f2d6a07e7dc1 HTTP/1.1

### 
GET {{baseUri}}/applications/{{sampleAppObjectId}} HTTP/1.1
Content-Type: {{contentType}}

###
# Adding an owner to the application
POST {{baseUri}}/applications/{{sampleAppObjectId}}/owners/{{userObjectId}} HTTP/1.1
Content-Type: application/json


###
# Deleting an owner to the application
DELETE {{baseUri}}/applications/{{sampleAppObjectId}}/owners/{{userObjectId}} HTTP/1.1
Content-Type: application/json




###
# Lists all Service Principals in the directory. However, this API 
# doesn't do paging, therefore, only the first page of info is returned.

GET {{baseUri}}/service-principals HTTP/1.1
Content-Type: {{contentType}}

### 
GET {{baseUri}}/service-principals/{{sampleSPObjectId}} HTTP/1.1
Content-Type: {{contentType}}

### 
GET {{baseUri}}/service-principals/app-ids/{{sampleAppId}} HTTP/1.1
Content-Type: {{contentType}}

###
POST {{baseUri}}/service-principals HTTP/1.1
Content-Type: application/json

{
    "Description": "Venus-X-ServicePrincipal",
    "AppId": "{{sampleAppId}}",
    "Tags": ["Venus", "Automated", "ServicePrincipal"]
}

###
POST {{baseUri}}/service-principals/{{sampleSPObjectId}}/password-credentials HTTP/1.1
Content-Type: application/json

{
    "DisplayName": "NextMonthPassword",
    "Hint": "This is my smart hint!",
    "StartDateTime": "6/21/2021 9:22:53 AM +00:00",
    "EndDateTime": "7/21/2021 9:22:53 AM +00:00"
}

###
DELETE {{baseUri}}/service-principals/{{sampleSPObjectId}}/password-credentials/ffdc63a6-6e70-42d2-8922-92d3f96c79d1 HTTP/1.1


###
# Adding an owner to the Service Principal
POST {{baseUri}}/service-principals/{{sampleSPObjectId}}/owners/{{userObjectId}} HTTP/1.1
Content-Type: application/json


###
# Deleting an owner to the Service Principal
DELETE {{baseUri}}/service-principals/{{sampleSPObjectId}}/owners/{{userObjectId}} HTTP/1.1
Content-Type: application/json